const DATA_URL='RentStabilized2025.geojson';
const YEARS=Array.from({length:18},(_,i)=>2008+i);
const COLORS={current:'#ff8c1a',former:'#ffd39a',other:'#fff4bf',outline:'#8d7b4b'};
const MANHATTAN_BOUNDS=[[-74.0479,40.6829],[-73.9067,40.8820]];
let rawData, map, summaryChart, historyChart, selectedId=null;
let currentYear=2025;
const activeCategories=new Set(['current','former','other']);
const els=Object.fromEntries([...document.querySelectorAll('[id]')].map(e=>[e.id,e]));
const nf=new Intl.NumberFormat('en-US');

function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function rsField(y){return `RS_${y}`}
function isResidential(p){const lu=String(p.LandUse??'').replace(/^0+/,'');return ['1','2','3','4'].includes(lu)||num(p.UnitsRes)>0}
function categoryFor(p,year){if(!isResidential(p))return'excluded';if(num(p[rsField(year)])>0)return'current';for(let y=2008;y<year;y++)if(num(p[rsField(y)])>0)return'former';return'other'}
function cdLabel(v){const s=String(v??'');if(!s)return'';const n=Number(s);if(n>=101&&n<=112)return`Manhattan Community District ${n-100}`;return`Community District ${s}`}
function bblString(v){return String(Math.trunc(num(v))).padStart(10,'0')}

async function init(){
  map=new maplibregl.Map({container:'map',style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',center:[-73.9712,40.7831],zoom:11.3,maxZoom:19});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');
  const r=await fetch(DATA_URL);rawData=await r.json();
  rawData.features.forEach((f,i)=>{f.id=i;f.properties.__residential=isResidential(f.properties)?1:0});
  populateFilters();
  map.on('load',()=>{map.addSource('lots',{type:'geojson',data:rawData,promoteId:'OBJECTID'});map.addLayer({id:'lots-fill',type:'fill',source:'lots',paint:{'fill-color':colorExpression(currentYear),'fill-opacity':.82}});map.addLayer({id:'lots-line',type:'line',source:'lots',paint:{'line-color':['case',['boolean',['feature-state','selected'],false],'#111111',COLORS.outline],'line-width':['case',['boolean',['feature-state','selected'],false],3,.25],'line-opacity':.62}});applyMapFilter();map.on('click','lots-fill',e=>{if(e.features?.[0])selectFeatureById(e.features[0].id,true)});map.on('mouseenter','lots-fill',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','lots-fill',()=>map.getCanvas().style.cursor='');updateSummary();});
  bindUI();
}

function colorExpression(year){const f=rsField(year);const prior=[];for(let y=2008;y<year;y++)prior.push(['>',['coalesce',['to-number',['get',rsField(y)]],0],0]);return['case',['>', ['coalesce',['to-number',['get',f]],0],0],COLORS.current,prior.length?['any',...prior]:false,COLORS.former,COLORS.other]}
function categoryFilterExpression(year){const conditions=[];if(activeCategories.has('current'))conditions.push(['>', ['coalesce',['to-number',['get',rsField(year)]],0],0]);if(activeCategories.has('former')){const prior=[];for(let y=2008;y<year;y++)prior.push(['>',['coalesce',['to-number',['get',rsField(y)]],0],0]);conditions.push(['all',['==',['coalesce',['to-number',['get',rsField(year)]],0],0],prior.length?['any',...prior]:false])}if(activeCategories.has('other')){const none=[];for(let y=2008;y<=year;y++)none.push(['==',['coalesce',['to-number',['get',rsField(y)]],0],0]);conditions.push(['all',...none])}return conditions.length?['any',...conditions]:['==',1,0]}
function applyMapFilter(){if(!map?.getLayer('lots-fill'))return;const filters=[['==',['get','__residential'],1],categoryFilterExpression(currentYear)];if(els.cdFilter.value)filters.push(['==',['to-string',['get','CD']],els.cdFilter.value]);if(els.ntaFilter.value)filters.push(['==',['get','NTA'],els.ntaFilter.value]);const filter=['all',...filters];map.setFilter('lots-fill',filter);map.setFilter('lots-line',filter)}
function populateFilters(){const cds=[...new Set(rawData.features.filter(f=>isResidential(f.properties)).map(f=>String(f.properties.CD)).filter(Boolean))].sort((a,b)=>Number(a)-Number(b));cds.forEach(v=>els.cdFilter.add(new Option(cdLabel(v),v)));const ntas=[...new Set(rawData.features.filter(f=>isResidential(f.properties)).map(f=>f.properties.NTA).filter(Boolean))].sort();ntas.forEach(v=>els.ntaFilter.add(new Option(v,v)))}
function filteredFeatures(){return rawData.features.filter(f=>isResidential(f.properties)&&(!els.cdFilter.value||String(f.properties.CD)===els.cdFilter.value)&&(!els.ntaFilter.value||f.properties.NTA===els.ntaFilter.value)&&activeCategories.has(categoryFor(f.properties,currentYear)))}
function updateSummary(){if(!rawData)return;const fs=filteredFeatures();let res=0,rs=0;fs.forEach(f=>{res+=num(f.properties.UnitsRes);rs+=num(f.properties[rsField(currentYear)])});const other=Math.max(0,res-rs);els.resUnits.textContent=nf.format(res);els.rsUnits.textContent=nf.format(rs);els.rsShare.textContent=res?`${(rs/res*100).toFixed(1)}%`:'0.0%';els.taxLotCount.textContent=nf.format(fs.length);els.summaryTitle.textContent=els.cdFilter.value?cdLabel(els.cdFilter.value):els.ntaFilter.value||'Manhattan';els.summaryYear.textContent=currentYear;
  const data={labels:['Rent-Stabilized Units','Other Residential Units'],datasets:[{data:[rs,other],backgroundColor:[COLORS.current,COLORS.other],borderColor:'#ffffff',borderWidth:2}]};if(summaryChart){summaryChart.data=data;summaryChart.update()}else summaryChart=new Chart(els.summaryChart,{type:'doughnut',data,options:{responsive:true,maintainAspectRatio:false,cutout:'63%',plugins:{legend:{position:'bottom',labels:{boxWidth:12,font:{size:10}}},tooltip:{callbacks:{label:c=>`${c.label}: ${nf.format(c.raw)} (${res?(c.raw/res*100).toFixed(1):0}%)`}}}}})}
function bindUI(){document.querySelectorAll('[data-category]').forEach(cb=>cb.addEventListener('change',()=>{cb.checked?activeCategories.add(cb.dataset.category):activeCategories.delete(cb.dataset.category);applyMapFilter();updateSummary()}));els.yearSlider.addEventListener('input',()=>{currentYear=Number(els.yearSlider.value);els.yearLabel.textContent=currentYear;if(map?.getLayer('lots-fill'))map.setPaintProperty('lots-fill','fill-color',colorExpression(currentYear));applyMapFilter();updateSummary();if(selectedId!==null)showDetails(rawData.features[selectedId])});els.cdFilter.addEventListener('change',()=>{if(els.cdFilter.value)els.ntaFilter.value='';applyMapFilter();updateSummary();zoomToFiltered()});els.ntaFilter.addEventListener('change',()=>{if(els.ntaFilter.value)els.cdFilter.value='';applyMapFilter();updateSummary();zoomToFiltered()});els.searchBtn.addEventListener('click',searchAddress);els.addressInput.addEventListener('keydown',e=>{if(e.key==='Enter')searchAddress()});els.closeDetails.addEventListener('click',()=>els.details.classList.remove('open'));els.resetView.addEventListener('click',()=>{els.cdFilter.value='';els.ntaFilter.value='';applyMapFilter();updateSummary();map.fitBounds(MANHATTAN_BOUNDS,{padding:24})});els.aboutBtn.addEventListener('click',()=>els.aboutDialog.showModal());els.closeAbout.addEventListener('click',()=>els.aboutDialog.close())}
function zoomToFiltered(){const fs=filteredFeatures();if(!fs.length)return;const b=new maplibregl.LngLatBounds();fs.forEach(f=>extendBounds(b,f.geometry.coordinates));if(!b.isEmpty())map.fitBounds(b,{padding:{top:40,bottom:80,left:40,right:40},maxZoom:15})}
function extendBounds(b,c){if(typeof c[0]==='number')b.extend(c);else c.forEach(x=>extendBounds(b,x))}
function selectFeatureById(id,zoom){const idx=rawData.features.findIndex(f=>String(f.properties.OBJECTID)===String(id)||String(f.id)===String(id));if(idx<0)return;if(selectedId!==null)map.setFeatureState({source:'lots',id:rawData.features[selectedId].properties.OBJECTID},{selected:false});selectedId=idx;const f=rawData.features[idx];map.setFeatureState({source:'lots',id:f.properties.OBJECTID},{selected:true});showDetails(f);if(zoom){const b=new maplibregl.LngLatBounds();extendBounds(b,f.geometry.coordinates);map.fitBounds(b,{padding:{top:80,bottom:80,left:80,right:430},maxZoom:17})}}
function showDetails(f){const p=f.properties;els.details.classList.add('open');els.detailsEmpty.hidden=true;els.detailsContent.hidden=false;els.detailAddress.textContent=p.Address||'Address unavailable';els.detailBbl.textContent=`BBL ${bblString(p.BBL)}`;els.detailGeo.textContent=[cdLabel(p.CD),p.NTA].filter(Boolean).join(' · ');els.detailUnitsRes.textContent=nf.format(num(p.UnitsRes));els.detailCurrentRs.textContent=nf.format(num(p[rsField(currentYear)]));els.detailCurrentLabel.textContent=`Rent Stabilized ${currentYear}`;const values=YEARS.map(y=>num(p[rsField(y)]));const chartData={labels:YEARS,datasets:[{label:'Rent-Stabilized Units',data:values,borderColor:COLORS.current,backgroundColor:'rgba(255,140,26,.12)',fill:true,tension:.18,pointRadius:2.5,pointHoverRadius:5,borderWidth:2}]};if(historyChart){historyChart.data=chartData;historyChart.update()}else historyChart=new Chart(els.historyChart,{type:'line',data:chartData,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${nf.format(c.raw)} units`}}},scales:{x:{grid:{display:false},ticks:{maxRotation:0,autoSkip:true,maxTicksLimit:7,font:{size:10}}},y:{beginAtZero:true,grid:{color:'rgba(0,0,0,.08)'},ticks:{precision:0,font:{size:10}}}}}});els.yearTable.innerHTML=YEARS.slice().reverse().map(y=>`<div class="year-row"><span>Rent Stabilized ${y}</span><strong>${nf.format(num(p[rsField(y)]))}</strong></div>`).join('')}
async function searchAddress(){const q=els.addressInput.value.trim();if(!q)return;els.searchStatus.textContent='Searching…';const local=rawData.features.find(f=>(f.properties.Address||'').toUpperCase()===q.toUpperCase());if(local){selectFeatureById(local.id,true);els.searchStatus.textContent='Address matched in the dataset.';return}const key=window.APP_CONFIG?.NYC_GEOCLIENT_KEY;if(!key||key.includes('PASTE_')){els.searchStatus.textContent='Add your NYC Geoclient subscription key in config.js to enable address geocoding.';return}const m=q.match(/^\s*([0-9]+[A-Za-z-]?)\s+(.+)$/);if(!m){els.searchStatus.textContent='Enter a house number and street name.';return}try{const url=new URL('https://api.nyc.gov/geo/geoclient/v2/address.json');url.searchParams.set('houseNumber',m[1]);url.searchParams.set('street',m[2]);url.searchParams.set('borough','manhattan');const r=await fetch(url,{headers:{'Ocp-Apim-Subscription-Key':key}});if(!r.ok)throw new Error(`Geocoder returned ${r.status}`);const j=await r.json();const a=j.address||j;let bbl=a.bbl;if(!bbl&&a.boroughCode&&a.taxBlock&&a.taxLot)bbl=`${a.boroughCode}${String(a.taxBlock).padStart(5,'0')}${String(a.taxLot).padStart(4,'0')}`;const idx=rawData.features.findIndex(f=>bblString(f.properties.BBL)===bblString(bbl));if(idx<0)throw new Error('The address was geocoded, but its BBL is not in this Manhattan dataset.');selectFeatureById(rawData.features[idx].id,true);els.searchStatus.textContent='Address located.'}catch(e){console.error(e);els.searchStatus.textContent=e.message||'Address could not be located.'}}
init().catch(e=>{console.error(e);document.body.innerHTML=`<p style="padding:30px">The dashboard could not load: ${e.message}</p>`});
