const METADATA_URL='./lots.json';
const TILE_URL='./tiles/{z}/{x}/{y}.pbf';
const YEARS=Array.from({length:18},(_,i)=>2008+i);
const COLORS={current:'#ff8c1a',former:'#ffd39a',other:'#fff4bf',outline:'#8d7b4b'};
const MANHATTAN_BOUNDS=[[-74.0479,40.6829],[-73.9067,40.8820]];
let lots=[],byBbl=new Map(),map,summaryChart,historyChart,selectedBbl=null,currentYear=2025;
const activeCategories=new Set(['current','former','other']);
const els=Object.fromEntries([...document.querySelectorAll('[id]')].map(e=>[e.id,e]));
const nf=new Intl.NumberFormat('en-US');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const rsField=y=>`RS_${y}`;
const bblString=v=>String(Math.trunc(num(v))).padStart(10,'0');
function categoryFor(p,year){if(num(p[rsField(year)])>0)return'current';for(let y=2008;y<year;y++)if(num(p[rsField(y)])>0)return'former';return'other'}
function cdLabel(v){const n=Number(v);return n>=101&&n<=112?`Manhattan Community District ${n-100}`:`Community District ${v}`}
function colorExpression(year){const prior=[];for(let y=2008;y<year;y++)prior.push(['>',['coalesce',['to-number',['get',rsField(y)]],0],0]);return['case',['>',['coalesce',['to-number',['get',rsField(year)]],0],0],COLORS.current,prior.length?['any',...prior]:false,COLORS.former,COLORS.other]}
function categoryFilterExpression(year){const c=[];if(activeCategories.has('current'))c.push(['>',['coalesce',['to-number',['get',rsField(year)]],0],0]);if(activeCategories.has('former')){const p=[];for(let y=2008;y<year;y++)p.push(['>',['coalesce',['to-number',['get',rsField(y)]],0],0]);c.push(['all',['==',['coalesce',['to-number',['get',rsField(year)]],0],0],p.length?['any',...p]:false])}if(activeCategories.has('other')){const p=[];for(let y=2008;y<=year;y++)p.push(['==',['coalesce',['to-number',['get',rsField(y)]],0],0]);c.push(['all',...p])}return c.length?['any',...c]:['==',1,0]}
function applyMapFilter(){if(!map?.getLayer('lots-fill'))return;const f=[categoryFilterExpression(currentYear)];if(els.cdFilter.value)f.push(['==',['to-string',['get','CD']],els.cdFilter.value]);if(els.ntaFilter.value)f.push(['==',['get','NTA'],els.ntaFilter.value]);map.setFilter('lots-fill',['all',...f]);map.setFilter('lots-line',['all',...f])}
function filteredLots(){return lots.filter(p=>(!els.cdFilter.value||String(p.CD)===els.cdFilter.value)&&(!els.ntaFilter.value||p.NTA===els.ntaFilter.value)&&activeCategories.has(categoryFor(p,currentYear)))}
function populateFilters(){[...new Set(lots.map(p=>String(p.CD)).filter(Boolean))].sort((a,b)=>+a-+b).forEach(v=>els.cdFilter.add(new Option(cdLabel(v),v)));[...new Set(lots.map(p=>p.NTA).filter(Boolean))].sort().forEach(v=>els.ntaFilter.add(new Option(v,v)))}
function updateSummary(){const fs=filteredLots();let res=0,rs=0;fs.forEach(p=>{res+=num(p.UnitsRes);rs+=num(p[rsField(currentYear)])});const other=Math.max(0,res-rs);els.resUnits.textContent=nf.format(res);els.rsUnits.textContent=nf.format(rs);els.rsShare.textContent=res?`${(rs/res*100).toFixed(1)}%`:'0.0%';els.taxLotCount.textContent=nf.format(fs.length);els.summaryTitle.textContent=els.cdFilter.value?cdLabel(els.cdFilter.value):els.ntaFilter.value||'Manhattan';els.summaryYear.textContent=currentYear;const data={labels:['Rent-Stabilized Units','Other Residential Units'],datasets:[{data:[rs,other],backgroundColor:[COLORS.current,COLORS.other],borderColor:'#fff',borderWidth:2}]};if(summaryChart){summaryChart.data=data;summaryChart.update()}else summaryChart=new Chart(els.summaryChart,{type:'doughnut',data,options:{responsive:true,maintainAspectRatio:false,cutout:'63%',plugins:{legend:{position:'bottom',labels:{boxWidth:12,font:{size:10}}},tooltip:{callbacks:{label:c=>`${c.label}: ${nf.format(c.raw)} (${res?(c.raw/res*100).toFixed(1):0}%)`}}}}})}
function zoomToFiltered(){const fs=filteredLots();if(!fs.length)return;const b=new maplibregl.LngLatBounds();fs.forEach(p=>b.extend([p.lon,p.lat]));map.fitBounds(b,{padding:{top:40,bottom:80,left:40,right:40},maxZoom:15})}
function selectLot(p,zoom=true){if(!p)return;selectedBbl=Number(p.BBL);if(map?.getLayer('lots-selected'))map.setFilter('lots-selected',['==',['to-string',['get','BBL']],String(selectedBbl)]);showDetails(p);if(zoom)map.flyTo({center:[p.lon,p.lat],zoom:17,essential:true})}
function showDetails(p){els.details.classList.add('open');els.detailsEmpty.hidden=true;els.detailsContent.hidden=false;els.detailAddress.textContent=p.Address||'Address unavailable';els.detailBbl.textContent=`BBL ${bblString(p.BBL)}`;els.detailGeo.textContent=[cdLabel(p.CD),p.NTA].filter(Boolean).join(' · ');els.detailUnitsRes.textContent=nf.format(num(p.UnitsRes));els.detailCurrentRs.textContent=nf.format(num(p[rsField(currentYear)]));els.detailCurrentLabel.textContent=`Rent Stabilized ${currentYear}`;const values=YEARS.map(y=>num(p[rsField(y)]));const d={labels:YEARS,datasets:[{data:values,borderColor:COLORS.current,backgroundColor:'rgba(255,140,26,.12)',fill:true,tension:.18,pointRadius:2.5,pointHoverRadius:5,borderWidth:2}]};if(historyChart){historyChart.data=d;historyChart.update()}else historyChart=new Chart(els.historyChart,{type:'line',data:d,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{maxRotation:0,autoSkip:true,maxTicksLimit:7,font:{size:10}}},y:{beginAtZero:true,grid:{color:'rgba(0,0,0,.08)'},ticks:{precision:0,font:{size:10}}}}}});els.yearTable.innerHTML=YEARS.slice().reverse().map(y=>`<div class="year-row"><span>Rent Stabilized ${y}</span><strong>${nf.format(num(p[rsField(y)]))}</strong></div>`).join('')}
async function searchAddress(){const q=els.addressInput.value.trim();if(!q)return;els.searchStatus.textContent='Searching…';const local=lots.find(p=>(p.Address||'').toUpperCase()===q.toUpperCase());if(local){selectLot(local);els.searchStatus.textContent='Address matched in the dataset.';return}const key=window.APP_CONFIG?.NYC_GEOCLIENT_KEY;if(!key){els.searchStatus.textContent='Add the NYC Geoclient key in config.js.';return}const m=q.match(/^\s*([0-9]+[A-Za-z-]?)\s+(.+)$/);if(!m){els.searchStatus.textContent='Enter a house number and street name.';return}try{const url=new URL('https://api.nyc.gov/geo/geoclient/v2/address.json');url.searchParams.set('houseNumber',m[1]);url.searchParams.set('street',m[2]);url.searchParams.set('borough','manhattan');url.searchParams.set('subscription-key',key);const r=await fetch(url);if(!r.ok){let detail='';try{detail=await r.text()}catch(_){ }if(r.status===401)throw new Error('Geocoder authorization failed (401). Confirm that this key is subscribed to the Geoclient V2 User product in the NYC API portal.');throw new Error(`Geocoder returned ${r.status}${detail?`: ${detail.slice(0,160)}`:''}`);}const j=await r.json(),a=j.address||j;let bbl=a.bbl;if(!bbl&&a.boroughCode&&a.taxBlock&&a.taxLot)bbl=`${a.boroughCode}${String(a.taxBlock).padStart(5,'0')}${String(a.taxLot).padStart(4,'0')}`;const p=byBbl.get(bblString(bbl));if(!p)throw new Error('The address was geocoded, but its BBL is not in this dataset.');selectLot(p);els.searchStatus.textContent='Address located.'}catch(e){els.searchStatus.textContent=e.message||'Address could not be located.'}}
function bindUI(){document.querySelectorAll('[data-category]').forEach(cb=>cb.addEventListener('change',()=>{cb.checked?activeCategories.add(cb.dataset.category):activeCategories.delete(cb.dataset.category);applyMapFilter();updateSummary()}));els.yearSlider.addEventListener('input',()=>{currentYear=+els.yearSlider.value;els.yearLabel.textContent=currentYear;map.setPaintProperty('lots-fill','fill-color',colorExpression(currentYear));applyMapFilter();updateSummary();if(selectedBbl)showDetails(byBbl.get(bblString(selectedBbl)))});els.cdFilter.addEventListener('change',()=>{if(els.cdFilter.value)els.ntaFilter.value='';applyMapFilter();updateSummary();zoomToFiltered()});els.ntaFilter.addEventListener('change',()=>{if(els.ntaFilter.value)els.cdFilter.value='';applyMapFilter();updateSummary();zoomToFiltered()});els.searchBtn.addEventListener('click',searchAddress);els.addressInput.addEventListener('keydown',e=>{if(e.key==='Enter')searchAddress()});els.closeDetails.addEventListener('click',()=>els.details.classList.remove('open'));els.resetView.addEventListener('click',()=>{els.cdFilter.value='';els.ntaFilter.value='';applyMapFilter();updateSummary();map.fitBounds(MANHATTAN_BOUNDS,{padding:24})});els.aboutBtn.addEventListener('click',()=>els.aboutDialog.showModal());els.closeAbout.addEventListener('click',()=>els.aboutDialog.close())}
async function init(){lots=await fetch(METADATA_URL).then(r=>r.json());lots.forEach(p=>byBbl.set(bblString(p.BBL),p));populateFilters();bindUI();map=new maplibregl.Map({container:'map',style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',center:[-73.9712,40.7831],zoom:11.3,maxZoom:19});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('error',e=>{console.error('Map error:',e?.error||e);const msg=e?.error?.message||'';if(msg.includes('tiles/')||msg.includes('.pbf'))els.searchStatus.textContent='Map tiles could not be loaded. Confirm that the complete tiles folder was uploaded with its nested folders.'});map.on('load',()=>{map.addSource('lots',{type:'vector',tiles:[TILE_URL],minzoom:11,maxzoom:15});map.addLayer({id:'lots-fill',type:'fill',source:'lots','source-layer':'lots',paint:{'fill-color':colorExpression(currentYear),'fill-opacity':.82}});map.addLayer({id:'lots-line',type:'line',source:'lots','source-layer':'lots',paint:{'line-color':COLORS.outline,'line-width':.25,'line-opacity':.62}});map.addLayer({id:'lots-selected',type:'line',source:'lots','source-layer':'lots',filter:['==',['to-string',['get','BBL']],''],paint:{'line-color':'#111','line-width':3,'line-opacity':1}});applyMapFilter();updateSummary();map.on('click','lots-fill',e=>{const b=e.features?.[0]?.properties?.BBL;if(b)selectLot(byBbl.get(bblString(b)),false)});map.on('mouseenter','lots-fill',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','lots-fill',()=>map.getCanvas().style.cursor='')})}
init().catch(e=>{console.error(e);document.body.innerHTML=`<p style="padding:30px">The dashboard could not load: ${e.message}</p>`});
